# Changie docs
# https://changie.dev/config
#
# Advanced formatting/logic docs
# https://masterminds.github.io/sprig
changesDir: changelog/releases
unreleasedDir: ../unreleased
headerPath: ../header.tpl.md
versionHeaderPath: ""
versionFooterPath: ""
changelogPath: CHANGELOG.md
versionExt: md
componentFormat: "### {{.Component}}"
versionFormat: |
  ## [{{.Version}}] _{{.Time.Format "2006-01-02"}}_
headerFormat: |
  Cycloid technical public changelog:
kindFormat: "**{{.Kind}}**"
changeFormat: "  - {{.Body}} ([FE#{{.Custom.PR}}])"
changeFormat: |
  {{- if eq .Custom.TYPE "FE" -}}
    - {{.Body}} ([FE#{{.Custom.PR}}])
  {{if ne .Custom.DETAILS "" -}}
  *{{.Custom.DETAILS}}*
  {{- end -}}
  {{- else -}}
    - {{.Body}} ([BE#{{.Custom.PR}}])
  {{- if ne .Custom.DETAILS "" -}}
  *{{.Custom.DETAILS}}*
  {{- end -}}
  {{- end -}}
footerFormat: |
  {{- range .Changes }}
  {{- if eq .Custom.TYPE "FE"}}
  [FE#{{.Custom.PR}}]: https://github.com/cycloidio/youdeploy-frontend-web/pull/{{.Custom.PR}}
  {{- else}}
  [BE#{{.Custom.PR}}]: https://github.com/cycloidio/youdeploy-http-api/pull/{{.Custom.PR}}
  {{- end}}
  {{- end}}
